#!/usr/bin/env bash
# shellcheck shell=bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

export PROJECT_ROOT
export CONDA_ENV_NAME="${CONDA_ENV_NAME:-diffusion-server}"
export TORCH_VARIANT="${TORCH_VARIANT:-cuda121}"  # cpu | cuda121

export PROTAC_CSV="${PROTAC_CSV:-${PROJECT_ROOT}/data/csv/protac.csv}"
export LINKER_CSV="${LINKER_CSV:-${PROJECT_ROOT}/data/csv/linker.csv}"

export WEAK_ANCHOR_OUT_DIR="${WEAK_ANCHOR_OUT_DIR:-${PROJECT_ROOT}/outputs/weak_anchor_best}"
export WEAK_ANCHOR_CSV="${WEAK_ANCHOR_CSV:-${WEAK_ANCHOR_OUT_DIR}/weak_anchor_dataset.csv}"
export WEAK_ANCHOR_REJ_CSV="${WEAK_ANCHOR_REJ_CSV:-${WEAK_ANCHOR_OUT_DIR}/weak_anchor_rejections.csv}"
export WEAK_ANCHOR_SUMMARY_JSON="${WEAK_ANCHOR_SUMMARY_JSON:-${WEAK_ANCHOR_OUT_DIR}/summary.json}"
export WEAK_ANCHOR_DEBUG_JSON="${WEAK_ANCHOR_DEBUG_JSON:-${WEAK_ANCHOR_OUT_DIR}/debug_examples.json}"
export WEAK_ANCHOR_TENSOR_PT="${WEAK_ANCHOR_TENSOR_PT:-${PROJECT_ROOT}/data/processed/weak_anchor_tensors.pt}"

export MAX_PAIRS="${MAX_PAIRS:-}"
export DEDUPE_PROTACS="${DEDUPE_PROTACS:-true}"
export DEDUPE_LINKERS="${DEDUPE_LINKERS:-true}"
export MIN_FRAGMENT_HEAVY_ATOMS="${MIN_FRAGMENT_HEAVY_ATOMS:-9}"
export MIN_LINKER_HEAVY_ATOMS="${MIN_LINKER_HEAVY_ATOMS:-8}"
export MIN_ANCHOR_GRAPH_DISTANCE="${MIN_ANCHOR_GRAPH_DISTANCE:-5}"
export MIN_LINKER_RATIO_PCT="${MIN_LINKER_RATIO_PCT:-15}"
export MAX_LINKER_RATIO_PCT="${MAX_LINKER_RATIO_PCT:-35}"
export LOG_NO_MATCH_REJECTIONS="${LOG_NO_MATCH_REJECTIONS:-false}"
export INCLUDE_PAIR_MASK="${INCLUDE_PAIR_MASK:-true}"

export CHECKPOINT_DIR="${CHECKPOINT_DIR:-${PROJECT_ROOT}/checkpoints}"
export NODE_CKPT="${NODE_CKPT:-${CHECKPOINT_DIR}/linker_node_diffusion.pt}"
export EDGE_CKPT="${EDGE_CKPT:-${CHECKPOINT_DIR}/linker_edge_diffusion.pt}"

export DEVICE="${DEVICE:-auto}"
export SEED="${SEED:-42}"

export NODE_EPOCHS="${NODE_EPOCHS:-100}"
export NODE_BATCH_SIZE="${NODE_BATCH_SIZE:-16}"
export NODE_LR="${NODE_LR:-2e-4}"
export NODE_WEIGHT_DECAY="${NODE_WEIGHT_DECAY:-1e-4}"
export NODE_HIDDEN_DIM="${NODE_HIDDEN_DIM:-128}"
export NODE_LAYERS="${NODE_LAYERS:-4}"
export NODE_DROPOUT="${NODE_DROPOUT:-0.1}"
export NODE_TIMESTEPS="${NODE_TIMESTEPS:-200}"
export NODE_BETA_START="${NODE_BETA_START:-1e-4}"
export NODE_BETA_END="${NODE_BETA_END:-0.02}"
export NODE_VAL_RATIO="${NODE_VAL_RATIO:-0.1}"
export NODE_MAX_SAMPLES="${NODE_MAX_SAMPLES:-}"

export EDGE_EPOCHS="${EDGE_EPOCHS:-100}"
export EDGE_BATCH_SIZE="${EDGE_BATCH_SIZE:-8}"
export EDGE_LR="${EDGE_LR:-2e-4}"
export EDGE_WEIGHT_DECAY="${EDGE_WEIGHT_DECAY:-1e-4}"
export EDGE_HIDDEN_DIM="${EDGE_HIDDEN_DIM:-128}"
export EDGE_LAYERS="${EDGE_LAYERS:-4}"
export EDGE_DROPOUT="${EDGE_DROPOUT:-0.1}"
export EDGE_TIMESTEPS="${EDGE_TIMESTEPS:-200}"
export EDGE_BETA_START="${EDGE_BETA_START:-1e-4}"
export EDGE_BETA_END="${EDGE_BETA_END:-0.02}"
export EDGE_VAL_RATIO="${EDGE_VAL_RATIO:-0.1}"
export EDGE_MAX_SAMPLES="${EDGE_MAX_SAMPLES:-}"

export SAMPLE_INDEX="${SAMPLE_INDEX:-0}"
export SAMPLE_ID="${SAMPLE_ID:-}"
export NUM_GENERATIONS="${NUM_GENERATIONS:-8}"
export EDGE_THRESHOLD="${EDGE_THRESHOLD:-0.5}"
export SAMPLE_SHOW_PROGRESS="${SAMPLE_SHOW_PROGRESS:-false}"
export SAMPLE_LOG_EVERY="${SAMPLE_LOG_EVERY:-20}"
export SAMPLE_SAVE_IMAGES="${SAMPLE_SAVE_IMAGES:-true}"
export SAMPLE_OUT_DIR="${SAMPLE_OUT_DIR:-${PROJECT_ROOT}/outputs/linker_sampling}"
